### ISSUE TITLE
Explosion not working due to plugin conflict

### ISSUE THREAD

**Issue by The-Nyla** [koiboi-dev/MissileWarfare#11]
## Description (Required)
The missiles fire correctly, do damage, and show explosion particles, but no actual damage is done to the terrain. this is most likely due to either griefprevention or worldguard, but nothing was shown-in-game or in server logs to point to a specific plugin

## Steps to reproduce the Issue (Required)
![image](https://user-images.githubusercontent.com/79489385/154550658-f8a10c5e-4431-47de-86de-6a4da79c710e.png)

## Expected behavior (Required)
the missile to blow up

## Server Log / Error Report
no errors or anything showed up in the log

## Environment (Required)
![image](https://user-images.githubusercontent.com/79489385/154551208-2c19fb7c-85d5-46e9-891a-f5041eff3ae2.png)
![image](https://user-images.githubusercontent.com/79489385/154551268-df8f4ae7-a3a9-45b1-afb4-32e1ac51b06b.png)

 - Minecraft Version: Purpur 1.18.1 build #1508
 - CS-CoreLib Version: none
 - Slimefun Version: DEV 999
 - Plugin Version: v1.2.2

**Comment by koiboi-dev** [comment]
I've created a possible fix for it, im unable to recreate the bug but i have changed the spawn explosion code to give information for why the explosion happened.
